### ISSUE TITLE
Videos can not being recorded with IE11 and Ziggeo V2

### ISSUE THREAD

**Issue by zyph00** [Ziggeo/ziggeo-client-sdk#13]
Hey guy's

Every time I start the ziggeo recorder on IE11 and press on 'record video' the following error message occurs:

![screen shot 2018-05-17 at 18 37 56](https://user-images.githubusercontent.com/8693771/40191348-855f7470-5a01-11e8-9c4d-2771d7c1d9e9.png)

The recorder doesn't show up. Just the loading animation is running endless.

I'm using the stable version of ziggeo v2.

I hope this helps to fix the bug.

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

Thank you for reporting this.

Just for sanity check, can you please try using the r31 as well and see if the same happens? With each version we patch anything that we find, so it might already be fixed in r31.

Also based on the error, it seems like there is a collision for names, so do you happen to have an element with ID `setLoopBack` in your own code by any chance?

I will also check on our side, however everything on our side is namespaces, so it should be safe from these things.

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

I've tried it with r31 and unfortunately it's still not working.

> Also based on the error, it seems like there is a collision for names, so do you happen to have an element with ID setLoopBack in your own code by any chance?

I've checked this and were not using it anywhere in the code.

> I will also check on our side, however everything on our side is namespaces, so it should be safe from these things.

Yes, no problem! :)

Regards,
Thomas

**Comment by zyph00** [comment]
I also got this message in the console:

![screen shot 2018-05-18 at 15 21 40](https://user-images.githubusercontent.com/8693771/40237081-a9b235f2-5aaf-11e8-87e7-ca796e679487.png)

**Comment by sambua** [comment]
Hi Thomas, 

Could you please provide with options you have set for the recorder and environment, so I could reproduce it? Also if you're using an emulator inside Edge or native IE?

Thanks in advance :) 

Regards,
Rashad

**Comment by ruiskeeled** [comment]
Hi,

I'm having the same problem.

Browsers:  IE11 and Edge
**vue-ziggeo: 1.0.2**

The recorder doesn't complete the load (keeps "loading") and it throws that error.

Let me know and thanks!

Best regards,
Rui

**Comment by Bane-D** [comment]
Hi Rui,

Thank you. We are looking into this and will follow up soon.

Are there any specific parameters that you are using, or ways you are testing it out?

Regards,
Bane
