### ISSUE TITLE
Recorder fails on Firefox [Nightly 63.0a1]

### ISSUE THREAD

**Issue by Splact** [Ziggeo/ziggeo-client-sdk#17]
Testing with [Ziggeo recorder demo](https://ziggeo.com/video-recorder#demo)
After camera and microphone access is given this error is thrown and the recorder is stuck on loading.

```
TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL.
```

Was happening on Firefox Nightly 63.0a1 (I've not the Firefox "stable" version installed to test atm).

**Comment by Bane-D** [comment]
Thank you for reporting this.

I am using the stable version and can not recreate it on my end. Will be great if you are able to test on stable version of Firefox just to confirm that this is related to the nightly version or not.

We will of course look into it, so again thank you for reporting it.

Regards,
Bane

**Comment by freitasskeeled** [comment]
Hi,

I'm having the same problem.

**Browser**: Firefox 62.0.3 (64-bit)
**vue-ziggeo**: 0.2.1

The recorder doesn't complete the load (keeps "loading") and it throws that error.

We are having that issue in production.

Let me know and thanks!

Best regards,
Freitas

**Comment by Bane-D** [comment]
Hi Freitas,

This has been solved and we have hot patched our stable and up revisions. I will check with our engineers if we need to make any changes on Vue end as well.

Regards,
Bane

**Comment by freitasskeeled** [comment]
Hi Bane,

I'm sorry to report that the problem is still happening. Did you release a new version? Or maybe the Vue wrapper needs to be changed?

Thanks.
Freitas

**Comment by sambua** [comment]
Hello Freitas ( @freitasskeeled  ),

Could you please upgrade to just published `vue-ziggeo 1.0.1`?

Thanks,
Rashad

**Comment by freitasskeeled** [comment]
Hey guys,

The issue seems to be fixed after upgrading to version 1.0.1.

Thanks!
